import tkinter
from tkinter import *
t=tkinter.Tk()
t.geometry('800x800')
t.title('Screen')
def first():
        a=Toplevel(t)
        a.geometry('700*700')
        a.config(bg='red')
        m=Label(a,texr='first screen')
        m.place(x=50,y=50)
        a.mainloop()
def second():
        a=Toplevel(t)
        a.geometry('700*700')
        a.config(bg='blue')
        m=Label(a,texr='second screen')
        m.place(x=50,y=50)
        a.mainloop()
def third():
        a=Toplevel(t)
        a.geometry('700*700')
        a.config(bg='blue')
        m=Label(a,texr='third screen')
        m.place(x=50,y=50)
        a.mainloop()
def forth():
        a=Toplevel(t)
        a.geometry('700*700')
        a.config(bg='blue')
        m=Label(a,texr='forth screen')
        m.place(x=50,y=50)
        a.mainloop()
a=Button(t,text='first',command=first)
a.place(x=100,y=60)
b=Button(t,text='second',command=second)
b.place(x=200,y=60)
c=Button(t,text='third',command=third)
c.place(x=100,y=100)
d=Button(t,text='forth',command=forth)
d.place(x=200,y=100)
t.mainloop()