import tkinter
from tkinter import*
import pymysql
from tkinter import messagebox
from tkinter import ttk
t=tkinter.Tk()
t.geometry('800x800')
t.title('p1')
def find():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    xa=int(ae.get())
    sql="select custname,address,phoneno,emailid from customer where custid=%d"%(xa)
    cur.execute(sql)
    data=cur.fetchone()
    be.insert(0,data[0])
    ce.insert(0,data[1])
    de.insert(0,data[2])
    ee.insert(0,data[3])
    db.close()
def deletedata():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    xa=int(ae.get())
    sql="delete from customer where custid=%d"%(xa)
    cur.execute(sql)
    db.commit()
    messagebox.showinfo('i','data deleted')
    ae.delete(0,100)
    be.delete(0,100)
    ce.delete(0,100)
    de.delete(0,100)
    ee.delete(0,100)
    db.close()
    
def close():
    t.destroy()
a=Label(t,text='customer id')
a.place(x=50,y=50)
ae=Entry(t,width=10)
ae.place(x=150,y=50)
ab=Button(t,text='find',command=find)
ab.place(x=260,y=50)
b=Label(t,text='customer name')
b.place(x=50,y=90)
be=Entry(t,width=10)
be.place(x=150,y=90)
c=Label(t,text='address')
c.place(x=50,y=130)
ce=Entry(t,width=10)
ce.place(x=150,y=130)
d=Label(t,text='phone no.')
d.place(x=50,y=180)
de=Entry(t,width=10)
de.place(x=150,y=180)
e=Label(t,text='emailid')
e.place(x=50,y=220)
ee=Entry(t,width=20)
ee.place(x=150,y=220)
btn=Button(t,text='close',command=close)
btn.place(x=50,y=320)
btn3=Button(t,text='delete',command=deletedata)
btn3.place(x=200,y=320)
t.mainloop()