import tkinter
from tkinter import*
import pymysql
from tkinter import messagebox
t=tkinter.Tk()
t.geometry('800x800')
t.title('billing')
def savedata():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    xa=int(ae.get())
    xb=be.get()
    xc=ce.get()
    xe=int(ee.get())
    xd=de.get()
    sql="insert into billing values('%d','%s','%s','%s','%d')"%(xa,xb,xc,xd,xe)
    cur.execute(sql)
    db.commit()
    messagebox.showinfo('hi','data saved')
    db.close
    ae.delete(0,100)
    be.delete(0,100)
    ce.delete(0,100)
    de.delete(0,100)
    ee.delete(0,100)
a=Label(t,text='billno')
a.place(x=50,y=50)
ae=Entry(t,width=10)
ae.place(x=150,y=50)
b=Label(t,text='customer name')
b.place(x=50,y=90)
be=Entry(t,width=10)
be.place(x=150,y=90)
c=Label(t,text='city')
c.place(x=50,y=130)
ce=Entry(t,width=10)
ce.place(x=150,y=130)
d=Label(t,text='mode')
d.place(x=50,y=180)
de=Entry(t,width=10)
de.place(x=150,y=180)
e=Label(t,text='bill amount')
e.place(x=50,y=220)
ee=Entry(t,width=20)
ee.place(x=150,y=220)
btn=Button(t,text='save',command=savedata)
btn.place(x=50,y=270)
t.mainloop()