import tkinter
from tkinter import *
from tkinter import ttk
t=tkinter.Tk()
t.geometry('800x800')
t.title("my")
a=Label(t,text='pythonfrom')
a.place(x=400,y=20)
b=Label(t,text='name')
b.place(x=50,y=60)
d=Entry(t,width=20)
d.place(x=500,y=60)
xp=IntVar()
r1=Radiobutton(t,text='male',variable=xp,value=1)
r2=Radiobutton(t,text='female',variable=xp,value=0)
r1.place(x=500,y=140)
r2.place(x=600,y=140)
h=Label(t,text='skill')
h.place(x=50,y=180)
lt=Listbox(t,height=3)
lt.Insert(1,'c')
lt.Insert(2,'c++')
lt.Insert(3,'java')
lt.place(x=500,y=180)
t.mainloop()
