 t.geometry('400x500')
 t.title('inventory')
 def insert():
     t=tkinter.Tk()
     t.geometry('800x800')
     t.title('billing')
     def savedata():
         db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
         cur=db.cursor()
         xa=int(ae.get())
         xb=int(be.get())
         xc=int(ce.get())
         xf=int(fe.get())
         xe=int(ee.get())
         xd=int(de.get())
         sql="insert into dispatch values('%d','%d','%d','%d','%d','%d')"%(xa,xb,xc,xf,xd,xe)
         cur.execute(sql)
         db.commit()
         messagebox.showinfo('hi','data saved')
         db.close
         dc.append(xa)
         ae.delete(0,100)
         be.delete(0,100)
         ce.delete(0,100)
         de.delete(0,100)
         fe.delete(0,100)
         ee.delete(0,100)
     a=Label(t,text='dispatchid')
     a.place(x=50,y=50)
     ae=Entry(t,width=10)
     ae.place(x=150,y=50)
     b=Label(t,text='orderid')
     b.place(x=50,y=90)
     be=Entry(t,width=10)
     be.place(x=150,y=90)
     c=Label(t,text='custid')
     c.place(x=50,y=130)
     ce=Entry(t,width=10)
     ce.place(x=150,y=130)
     f=Label(t,text='productid')
     f.place(x=50,y=180)
     fe=Entry(t,width=5)
     fe.place(x=150,y=180)
     d=Label(t,text='qty')
     d.place(x=50,y=220)
     de=Entry(t,width=10)
     de.place(x=150,y=220)
     e=Label(t,text='billamount')
     e.place(x=50,y=270)
     ee=Entry(t,width=20)
     ee.place(x=150,y=270)
     btn=Button(t,text='save',command=savedata)
     btn.place(x=50,y=320)
     t.mainloop()
 def removedata():
     dc.clear()
 def filldata():
     db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
     cur=db.cursor()
     sql="select dispatchno from dispatch"
     cur.execute(sql)
     data=cur.fetchall()
     for i in data:
         dc.append(i)
 def deletedata():
     filldata()
     t=tkinter.Tk()
     t.geometry('800x800')
     t.title('p1')
     def deletedata():
         db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
         cur=db.cursor()
         xa=int(ae.get())
         sql="delete from dispatch where dispatchno=%d"%(xa)
         cur.execute(sql)
         db.commit()
         messagebox.showinfo('i','data deleted')
         removedata()
         ae.delete(0,100)
         
     def close():
         removedata()
         t.destroy()
     a=Label(t,text='dispatchno')
     a.place(x=50,y=50)
     ae=ttk.Combobox(t)
     ae['values']=dc
     ae.place(x=150,y=50)
     btn=Button(t,text='close',command=close)
     btn.place(x=50,y=320)
     btn3=Button(t,text='delete',command=deletedata)
     btn3.place(x=200,y=320)
     t.mainloop()
 
 def find():
     filldata()
     global sc
     t=tkinter.Tk()
     t.geometry('800x800')
     t.title('p1')
     def find():
         db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
         cur=db.cursor()
         xa=int(ae.get())
         sql="select ordereid,cust,productid,qty,billamount from dispatch where dispatchno=%d"%(xa)
         cur.execute(sql)
         data=cur.fetchone()
         be.insert(0,str(data[0]))
         ce.insert(0,str(data[1]))
         de.insert(0,str(data[2]))
         ee.insert(0,str(data[3]))
         fe.insert(0,str(data[4]))
         db.close()
     def newdata():
         ae.delete(0,100)
         be.delete(0,100)
         ce.delete(0,100)
         de.delete(0,100)
         ee.delete(0,100)
         fe.delete(0,100)
     def close():
         removedata()
         t.destroy()
     t.config(bg='red')
     a=Label(t,text='dispatch no.')
     a.place(x=50,y=50)
     ae=ttk.Combobox(t)
     ae['values']=dc
     ae.place(x=150,y=50)
     ab=Button(t,text='find',command=find)
     ab.place(x=300,y=50)
     b=Label(t,text='order id')
     b.place(x=50,y=90)
     be=Entry(t,width=10)
     be.place(x=150,y=90)
     c=Label(t,text='customer id')
     c.place(x=50,y=130)
     ce=Entry(t,width=10)
     ce.place(x=150,y=130)
     d=Label(t,text='product id')
     d.place(x=50,y=180)
     de=Entry(t,width=10)
     de.place(x=150,y=180)
     e=Label(t,text='quantity')
     e.place(x=50,y=220)
     ee=Entry(t,width=20)
     ee.place(x=150,y=220)
     f=Label(t,text='billamount')
     f.place(x=50,y=270)
     fe=Entry(t,width=10)
     fe.place(x=150,y=270)
     btn=Button(t,text='close',command=close)
     btn.place(x=50,y=320)
     btn2=Button(t,text='new',command=newdata)
     btn2.place(x=150,y=320)
     t.mainloop()
 def show():
     t=tkinter.Tk()
     t.geometry('800x800')
     t.title('Data Show')
     aa=[]
     ab=[]
     ac=[]
     ad=[]
     ae=[]
     af=[]
     i=0
     def filldata():
         db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
         cur=db.cursor()
         sql="select dispatchno,ordereid,cust,productid,qty,billamount from dispatch"
         cur.execute(sql)
         data=cur.fetchall()
         global i
         for res in data:
             aa.append(res[0])
             ab.append(res[1])
             ac.append(res[2])
             ad.append(res[3])
             ae.append(res[4])
             af.append(res[5])
         db.close()
     def firstrecord():
         global i
         i=0
         b.config(text='')
         d.config(text='')
         f.config(text='')
         h.config(text='')
         beie.config(text='')
         xee.config(text='')
         
         b.config(text=aa[i])
         d.config(text=ab[i])
         f.config(text=ac[i])
         h.config(text=ad[i])
         beie.config(text=ae[i])
         xee.config(text=af[i])
         
     def nextrecord():
         global i
         i=i+1
         b.config(text='')
         d.config(text='')
         f.config(text='')
         h.config(text='')
         beie.config(text='')
         xee.config(text='')
         
         b.config(text=aa[i])
         d.config(text=ab[i])
         f.config(text=ac[i])
         h.config(text=ad[i])
         beie.config(text=ae[i])
         xee.config(text=af[i])
     def prevrecord():
         global i
         i=i-1
         b.config(text='')
         d.config(text='')
         f.config(text='')
         h.config(text='')
         beie.config(text='')
         xee.config(text='')
         
         b.config(text=aa[i])
         d.config(text=ab[i])
         f.config(text=ac[i])
         h.config(text=ad[i])
         beie.config(text=ae[i])
         xee.config(text=af[i])
     def lastrecord():
         global i
         i=len(aa)-1
         b.config(text='')
         d.config(text='')
         f.config(text='')
         h.config(text='')
         beie.config(text='')
         xee.config(text='')
         
         b.config(text=aa[i])
         d.config(text=ab[i])
         f.config(text=ac[i])
         h.config(text=ad[i])
         beie.config(text=ae[i])
         xee.config(text=af[i])

     a=Label(t,text='dispatchno')
     a.place(x=20,y=50)
     b=Label(t,width=30,fg='blue')
     b.place(x=500,y=50)
     c=Label(t,text='ordereid')
     c.place(x=20,y=150)
     d=Label(t,width=30)
     d.place(x=500,y=150)
     e=Label(t,text='cust')
     e.place(x=20,y=200)
     f=Label(t,width=30)
     f.place(x=500,y=200)
     g=Label(t,text='productid')
     g.place(x=20,y=250)
     h=Label(t,width=30)
     h.place(x=500,y=250)
     bei=Label(t,text='qty')
     bei.place(x=20,y=290)
     beie=Label(t,width=20)
     beie.place(x=500,y=290)
     x=Label(t,text='billamount')
     x.place(x=20,y=340)
     xee=Label(t,width=10)
     xee.place(x=500,y=340)
     k=Button(t,text='First',command=firstrecord)
     k.place(x=100,y=400)
     n=Button(t,text='Next',command=nextrecord)
     n.place(x=200,y=400)
     p=Button(t,text='Previous',command=prevrecord)
     p.place(x=300,y=400)
     r=Button(t,text='Last',command=lastrecord)
     r.place(x=400,y=400)
     filldata()
     t.mainloop()