import tkinter
from tkinter import*
import pymysql
from tkinter import messagebox
from tkinter import ttk
t=tkinter.Tk()
t.geometry('800x800')
t.title('p1')
def find():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    xa=int(ae.get())
    sql="select name,address,phone,email,regno from storeinfo where storeid=%d"%(xa)
    cur.execute(sql)
    data=cur.fetchone()
    be.insert(0,data[0])
    ce.insert(0,data[1])
    de.insert(0,data[2])
    ee.insert(0,data[3])
    fe.insert(0,str(data[4]))
    db.close()
def newdata():
    ae.delete(0,100)
    be.delete(0,100)
    ce.delete(0,100)
    de.delete(0,100)
def close():
    t.destroy()
a=Label(t,text='storeid')
a.place(x=50,y=50)
ae=ttk.Combobox()
ae['values']=se
ae.place(x=150,y=50)
ab=Button(t,text='find',command=find)
ab.place(x=260,y=50)
b=Label(t,text='name')
b.place(x=50,y=90)
be=Entry(t,width=10)
be.place(x=150,y=90)
c=Label(t,text='address')
c.place(x=50,y=130)
ce=Entry(t,width=10)
ce.place(x=150,y=130)
d=Label(t,text='phone')
d.place(x=50,y=180)
de=Entry(t,width=10)
de.place(x=150,y=180)
e=Label(t,text='email')
e.place(x=50,y=220)
ee=Entry(t,width=20)
ee.place(x=150,y=220)
f=Label(t,text='registration no.')
f.place(x=50,y=270)
fe=Entry(t,width=10)
btn=Button(t,text='close',command=close)
btn.place(x=50,y=320)
btn2=Button(t,text='new',command=newdata)
btn2.place(x=150,y=320)
btn3=Button(t,text='t'
btn3.place(x=200,y=270)
t.mainloop()
