import tkinter
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
import pymysql
t=tkinter.Tk()
t.geometry('500x300')
t.title('insert')
sc=['101']
def trydash():
    x=b.get()
    if x=='storeinfo':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('dashboard storeinfo')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                xf=int(fe.get())
                xe=int(ee.get())
                xd=de.get()
                sql="insert into storeinfo values('%d','%s','%s','%d','%s','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='storeid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='phone no')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='email')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='regno')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def delete():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select name,address,phone,email,regno from storeinfo where storeid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,data[0])
                ce.insert(0,data[1])
                de.insert(0,data[2])
                ee.insert(0,data[3])
                fe.insert(0,str(data[4]))
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from storeinfo where storeid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                fe.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='storeid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='phoneno')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='email')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='registration no.')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            fe.place(x=150,y=270)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        def find():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select name,address,phone,email,regno from storeinfo where storeid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,data[0])
                ce.insert(0,data[1])
                de.insert(0,data[2])
                ee.insert(0,data[3])
                fe.insert(0,str(data[4]))
                db.close()
            def newdata():
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
            def close():
                t.destroy()
            a=Label(t,text='storeid')
            a.place(x=50,y=50)
            ae=ttk.Combobox()
            ae['values']=se
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='phone')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='email')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='registration no.')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn2=Button(t,text='new',command=newdata)
            btn2.place(x=150,y=320)
            btn3=Button(t,text='t'
            btn3.place(x=200,y=270)
            t.mainloop()

                        
        t.config(bg='silver')
        d=Label(t,text='storeinfo',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='grey')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=delete)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='productcategory':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                sql="insert into productcategory values('%d','%s','%s')"%(xa,xb,xc)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
            a=Label(t,text='catid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='categoryname')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Discription')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=180)
            t.mainloop()
        def delete():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select catname,discription from productcategory where catid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,data[0])
                ce.insert(0,data[1])
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from productcategory where catid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='category id')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='category name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='discription')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='gold')
        d=Label(t,text='productcategory',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=delete)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='products':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=int(be.get())
                xc=ce.get()
                xf=int(fe.get())
                xe=int(ee.get())
                xd=de.get()
                sql="insert into products values('%d','%d','%s','%d','%s','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='productid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='categoryid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Product name')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='price')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='unit')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='qty')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def delete():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select catid,pname,price,unit,qty from products where productid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,str(data[0]))
                ce.insert(0,data[1])
                de.insert(0,str(data[2]))
                ee.insert(0,data[3])
                fe.insert(0,str(data[4]))
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from products where productid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                fe.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='productid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='category id')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='pname')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='price')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='unit')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='quantity')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            fe.place(x=150,y=270)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='red')
        d=Label(t,text='products',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=delete)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='supplier':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                xf=int(fe.get())
                xe=int(ee.get())
                xd=de.get()
                sql="insert into supplier values('%d','%s','%s','%d','%s','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='Supplierid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='Suppliername')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='phone')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='email')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='regno')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def delete():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select supplyname,supplyaddress,phoneno,emailid,registrationno from supplier where supplyid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,data[0])
                ce.insert(0,data[1])
                de.insert(0,data[2])
                ee.insert(0,data[3])
                fe.insert(0,str(data[4]))
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from supplier where supplyid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                fe.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='supplierid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='supplier name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='phone no.')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='emailid')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='registration no.')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            fe.place(x=150,y=270)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='blue')
        d=Label(t,text='supplier',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=delete)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='customer':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                xf=int(fe.get())
                xd=de.get()
                sql="insert into customer values('%d','%s','%s','%d','%s')"%(xa,xb,xc,xf,xd)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
            a=Label(t,text='Customerid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='Customername')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='phone')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='email')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def deletedata():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select custname,address,phoneno,emailid from customer where custid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,data[0])
                ce.insert(0,data[1])
                de.insert(0,data[2])
                ee.insert(0,data[3])
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from customer where custid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='customer id')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='customer name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='phone no.')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='emailid')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='darkgreen')
        d=Label(t,text='productcategory',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=deletedata)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='stockin':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=int(be.get())
                xc=int(ce.get())
                xf=fe.get()
                xe=int(ee.get())
                xd=int(de.get())
                sql="insert into stockin values('%d','%d','%d','%s','%d','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='stockid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='catid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Productid')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='productname')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='datein')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='qty')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def deletedata():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select catid,productid,pname,datein,qty from stockin where stockid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,str(data[0]))
                ce.insert(0,str(data[1]))
                de.insert(0,data[2])
                ee.insert(0,str(data[3]))
                ge.insert(0,str(data[4]))
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from stockin where stockid=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='stock id')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='catid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='productid')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='pname')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='datein')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            g=Label(t,text='qty')
            g.place(x=50,y=260)
            ge=Entry(t,width=20)
            ge.place(x=150,y=260)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='aqua')
        d=Label(t,text='stockin',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='orders':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=int(be.get())
                xc=int(ce.get())
                xf=int(fe.get())
                xe=int(ee.get())
                xd=int(de.get())
                xg=int(ge.get())
                sql="insert into orders values('%d','%d','%d','%d','%d','%d','%d')"%(xa,xb,xc,xf,xd,xe,xg)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
                ge.delete(0,100)
            a=Label(t,text='orderid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='custid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='date')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='order')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='catid')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='productid')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            g=Label(t,text='qty')
            g.place(x=50,y=320)
            ge=Entry(t,width=20)
            ge.place(x=150,y=320)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=370)
            t.mainloop()
        t.config(bg='black')
        d=Label(t,text='orders',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='dispatch':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=int(be.get())
                xc=int(ce.get())
                xf=int(fe.get())
                xe=int(ee.get())
                xd=int(de.get())
                sql="insert into dispatch values('%d','%d','%d','%d','%d','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='dispatchid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='orderid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='custid')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='productid')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='qty')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='billamount')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
        def deletedata():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select ordereid,cust,productid,qty,billamount from dispatch where dispatchno=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,str(data[0]))
                ce.insert(0,str(data[1]))
                de.insert(0,str(data[2]))
                ee.insert(0,str(data[3]))
                ge.insert(0,str(data[4]))
                db.close()
            def deletedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="delete from dispatch where dispatchno=%d"%(xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('i','data deleted')
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                ge.delete(0,100)
                db.close()
                
            def close():
                t.destroy()
            a=Label(t,text='dispatchno')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='ordereid')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='cust')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='productid')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='qty')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            g=Label(t,text='billamount')
            g.place(x=50,y=260)
            ge=Entry(t,width=20)
            ge.place(x=150,y=260)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='delete',command=deletedata)
            btn3.place(x=200,y=320)
            t.mainloop()
        t.config(bg='orange')
        d=Label(t,text='dispatch',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue',command=deletedata)
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
        
t.config(bg='pink')
a=Label(t,text='select table',font=30)
a.place(x=50,y=50)
b=ttk.Combobox(t)
b['values']=['storeinfo','productcategory','products','supplier','customer','stockin','orders','dispatch']
b.place(x=300,y=50)
btn=Button(t,text='enter',bg='lightblue',command=trydash)
btn.place(x=250,y=150)


t.mainloop()