import tkinter
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
import pymysql
t=tkinter.Tk()
t.geometry('800x8000')
t.title('dashboard')
sc=[]
pc=[]
psc=[]
sp=[]
cc=[]
si=[]
oc=[]
dc=[]
def insert():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('dashboard storeinfo')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        xf=fe.get()
        xe=int(ee.get())
        xd=de.get()
        sql="insert into storeinfo values('%d','%s','%s','%s','%s','%d')"%(xa,xb,xc,xf,xd,xe)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        sc.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
    def close():
        t.destroy()
    t.config(bg='darkgreen')
    a=Label(t,text='storeid',font='arial',fg='mediumblue',bg='darkgreen')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='name',font='arial',fg='mediumblue',bg='darkgreen')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='address',font='arial',fg='mediumblue',bg='darkgreen')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='phone no',font='arial',fg='mediumblue',bg='darkgreen')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='email',font='arial',fg='mediumblue',bg='darkgreen')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    e=Label(t,text='regno',font='arial',fg='mediumblue',bg='darkgreen')
    e.place(x=50,y=270)
    ee=Entry(t,width=20)
    ee.place(x=150,y=270)
    btn=Button(t,text='save',command=savedata,fg='yellow',bg='mediumblue')
    btn.place(x=50,y=320)
    btn1=Button(t,text='close',command=close,fg='yellow',bg='mediumblue')
    btn1.place(x=100,y=320)
    t.mainloop()
def removedata():
    sc.clear()
def filldata():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select storeid from storeinfo"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        sc.append(i)
            
    
        
    db.close()
def delete():
    removedata()
    filldata()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xs=str(xa)
        sql="delete from storeinfo where storeid=%d"%(xa)
        cur.execute(sql)
        db.commit
        messagebox.showinfo('i','data deleted')
        removedata()
        db.close()
        ae.delete(0,100)
        
    def close():
        removedata()
        t.destroy()
    t.config(bg='darkgreen')
    a=Label(t,text='storeid',font='arial',fg='mediumblue',bg='darkgreen')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=sc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',fg='yellow',bg='mediumblue',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',fg='yellow',bg='mediumblue',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def find():
    filldata()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select name,address,phone,email,regno from storeinfo where storeid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedata()
        t.destroy()
    t.config(bg='darkgreen')
    a=Label(t,text='storeid',font='arial',fg='mediumblue',bg='darkgreen')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=sc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='name',font='arial',fg='mediumblue',bg='darkgreen')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='address',font='arial',fg='mediumblue',bg='darkgreen')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='phone',font='arial',fg='mediumblue',bg='darkgreen')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='email',font='arial',fg='mediumblue',bg='darkgreen')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='registration no.',font='arial',fg='mediumblue',bg='darkgreen')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',fg='yellow',bg='mediumblue',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',fg='yellow',bg='mediumblue',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def updatedata():
    filldata()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select name,address,phone,email,regno from storeinfo where storeid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        xd=de.get()
        xe=ee.get()
        xf=int(fe.get())
        sql="update storeinfo set name='%s',address='%s',phone='%s',email='%s',regno=%d where storeid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        removedata()
        t.destroy()
    t.config(bg='darkgreen')
    a=Label(t,text='storeid',font='arial',fg='mediumblue',bg='darkgreen')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=sc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=400,y=50)
    b=Label(t,text='name',font='arial',fg='mediumblue',bg='darkgreen')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='address',font='arial',fg='mediumblue',bg='darkgreen')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='phoneno',font='arial',fg='mediumblue',bg='darkgreen')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='email',font='arial',fg='mediumblue',bg='darkgreen')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='registration no.',font='arial',fg='mediumblue',bg='darkgreen')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',fg='yellow',bg='mediumblue',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',fg='yellow',bg='mediumblue',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def show():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select storeid,name,address,phone,email,regno from storeinfo"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def close():
        t.destroy()


    t.config(bg='darkgreen')
    a=Label(t,text='storeid',font='arial',fg='mediumblue',bg='darkgreen')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='Name',font='arial',fg='mediumblue',bg='darkgreen')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='address',font='arial',fg='mediumblue',bg='darkgreen')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='phone',font='arial',fg='mediumblue',bg='darkgreen')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='email',font='arial',fg='mediumblue',bg='darkgreen')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='registration no',font='arial',fg='mediumblue',bg='darkgreen')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',fg='yellow',bg='mediumblue',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',fg='yellow',bg='mediumblue',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',fg='yellow',bg='mediumblue',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',fg='yellow',bg='mediumblue',command=lastrecord)
    r.place(x=400,y=400)
    rb=Button(t,text='close',fg='yellow',bg='mediumblue',command=close)
    rb.place(x=500,y=400)
    filldata()
    t.mainloop()
def insertcat():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('billing')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        sql="insert into productcategory values('%d','%s','%s')"%(xa,xb,xc)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        pc.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
    def close():
        t.destroy()
    t.config(bg='cyan')
    a=Label(t,text='catid',font='arial',fg='maroon',bg='cyan')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='categoryname',font='arial',fg='maroon',bg='cyan')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='Discription',font='arial',fg='maroon',bg='cyan')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    btn=Button(t,text='save',fg='yellow',bg='maroon',command=savedata)
    btn.place(x=50,y=180)
    btn1=Button(t,text='close',fg='yellow',bg='maroon',command=close)
    btn1.place(x=150,y=180)
    t.mainloop()
def removedatacat():
    pc.clear()
def filldatacat():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select catid from productcategory"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        pc.append(i)
def deletecat():
    filldatacat()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from productcategory where catid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatacat()
        ae.delete(0,100)
        db.close()
        
    def close():
        t.destroy()
    a=Label(t,text='category id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=pc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',fg='yellow',bg='maroon',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',fg='yellow',bg='maroon',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def findcat():
    filldatacat()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catname,discription from productcategory where catid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
    def close():
        removedatacat()
        t.destroy()
    a=Label(t,text='catid')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=pc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',fg='yellow',bg='maroon',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='catname')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='discription')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    btn=Button(t,text='close',fg='yellow',bg='maroon',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',fg='yellow',bg='maroon',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def closed():
    t.destroy()
def updatedatacat():
    filldatacat()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catname,discription from productcategory where catid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        sql="update productcategory set catname='%s',discription='%s' where catid=%d"%(xb,xc,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        removedatacat()
        t.destroy()
    a=Label(t,text='category id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=pc
    ae.place(x=150,y=50)
    ab=Button(t,text='showdata',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='category name')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='discription')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def showcat():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select catid,catname,discription from productcategory"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
    def close():
        t.destroy()

    a=Label(t,text='category id')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='category Name')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='discription')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    k=Button(t,text='First',fg='yellow',bg='maroon',command=firstrecord)
    k.place(x=100,y=270)
    n=Button(t,text='Next',fg='yellow',bg='maroon',command=nextrecord)
    n.place(x=200,y=270)
    p=Button(t,text='Previous',fg='yellow',bg='maroon',command=prevrecord)
    p.place(x=300,y=270)
    r=Button(t,text='Last',fg='yellow',bg='maroon',command=lastrecord)
    r.place(x=400,y=270)
    btn=Button(t,text='close',fg='yellow',bg='maroon',command=close)
    btn.place(x=500,y=270)
    filldata()
    t.mainloop()
def insertpr():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('billing')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=int(be.get())
        xc=ce.get()
        xf=int(fe.get())
        xe=int(ee.get())
        xd=de.get()
        sql="insert into products values('%d','%d','%s','%d','%s','%d')"%(xa,xb,xc,xf,xd,xe)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
    a=Label(t,text='productid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='categoryid')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='Product name')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='price')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='unit')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    e=Label(t,text='qty')
    e.place(x=50,y=270)
    ee=Entry(t,width=20)
    ee.place(x=150,y=270)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=320)
    t.mainloop()
def removedatapr():
    psc.clear()
def filldatapr():
   db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
   cur=db.cursor()
   sql="select productid from products"
   cur.execute(sql)
   data=cur.fetchall()
   for i in data:
       psc.append(i)
       db.close()
def deletepr():
    filldatapr()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from products where productid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatapr()
        ae.delete(0,100)
        db.close()
        
    def close():
        removedatapr()
        t.destroy()
    a=Label(t,text='productid')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=psc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def findpr():
    filldatapr()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catid,pname,price,unit,qty from products where productid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,str(data[0]))
        ce.insert(0,data[1])
        de.insert(0,str(data[2]))
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedatapr()
        t.destroy()
    a=Label(t,text='product id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=psc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='catid')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='pname')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='price')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='unit')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def updatedatapr():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catid,pname,price,unit,qty from products where productid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=int(be.get())
        xc=ce.get()
        xd=int(de.get())
        xe=ee.get()
        xf=int(fe.get())
        sql="update products set catid=%d,pname='%s',price=%d,unit='%s',qty=%d where productid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        t.destroy()
    a=Label(t,text='productid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    ab=Button(t,text='showdata',command=find)
    ab.place(x=260,y=50)
    b=Label(t,text='category id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='product name')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='price')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='unit')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def showpr():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select productid,catid,pname,price,unit,qty from products"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])

    a=Label(t,text='productid')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='category id')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='product name')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='price')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='unit')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='qty')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
def insertsp():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('billing')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        xf=fe.get()
        xe=int(ee.get())
        xd=de.get()
        sql="insert into supplier values('%d','%s','%s','%s','%s','%d')"%(xa,xb,xc,xf,xd,xe)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        sp.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
    a=Label(t,text='Supplierid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='Suppliername')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='Address')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='phone')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='email')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    e=Label(t,text='regno')
    e.place(x=50,y=270)
    ee=Entry(t,width=20)
    ee.place(x=150,y=270)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=320)
    t.mainloop()
def removedatasp():
    sp.clear()
def filldatasp():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select supplyid from supplier"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        sp.append(i)
def deletesp():
    filldatasp()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from supplier where supplyid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatasp()
        ae.delete(0,100)
        db.close()
        
    def close():
        removedatasp()
        t.destroy()
    a=Label(t,text='supplierid')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=sp
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def findsp():
    filldatasp()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select supplyname,supplyaddress,phoneno,emailid,registrationno from supplier where supplyid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedatasp()
        t.destroy()
    a=Label(t,text='supplier id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=sp
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='supplier name')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='supplier address')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='phone no')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='emailid')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='registration no.')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def updatedatasp():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select supplyname,supplyaddress,phoneno,emailid,registrationno from supplier where supplyid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        xd=de.get()
        xe=ee.get()
        xf=int(fe.get())
        sql="update supplier set supplyname='%s',supplyaddress='%s',phoneno='%s',emailid='%s',registrationno=%d where supplyid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        t.destroy()
    a=Label(t,text='supplier id')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    ab=Button(t,text='showdata',command=find)
    ab.place(x=260,y=50)
    b=Label(t,text='supplier name')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='supplier address')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='phoneno')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='emailid')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='registration no')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def showsp():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select supplyid,supplyname,supplyaddress,phoneno,emailid,registrationno from supplier"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])

    a=Label(t,text='supplyid ')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='supplyname')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='supplyaddress ')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='phoneno')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='emailid')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='registrationno')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
def insertcc():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('customer')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=be.get()
        xc=ce.get()
        xf=fe.get()
        xd=de.get()
        sql="insert into customer values('%d','%s','%s','%s','%s')"%(xa,xb,xc,xf,xd)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        cc.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
    a=Label(t,text='Customerid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='Customername')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='Address')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='phone')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='email')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=320)
    t.mainloop()
def removedatacc():
    cc.clear()
def filldatacc():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select custid from customer"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        cc.append(i)
def deletedatacc():
    filldatacc()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from customer where custid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        cc.remove(xa)
        ae.delete(0,100)
        removedatacc()
        db.close()
        
    def close():
        removedatacc()
        t.destroy()
    a=Label(t,text='customer id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=cc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()



def findcc():
    filldatacc()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select custname,address,phoneno,emailid from customer where custid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
    def close():
        removedatacc()
        t.destroy()
    a=Label(t,text='customer id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=cc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='customer name')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='customer address')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='phone no')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='emailid')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def showcc():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select custid,custname,address,phoneno,emailid from customer"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])

    a=Label(t,text='customer id ')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='customer name')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='address ')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='phoneno')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='emailid')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
def insertss():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('billing')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=int(be.get())
        xc=int(ce.get())
        xf=fe.get()
        xe=int(ee.get())
        xd=de.get()
        sql="insert into stockin values('%d','%d','%d','%s','%s','%d')"%(xa,xb,xc,xf,xd,xe)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        si.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
    a=Label(t,text='stockid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='catid')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='Productid')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='productname')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='datein')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    e=Label(t,text='qty')
    e.place(x=50,y=270)
    ee=Entry(t,width=20)
    ee.place(x=150,y=270)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=320)
    t.mainloop()
def removedatass():
    si.clear()
def filldatass():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select stockid from stockin"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        si.append(i)
def deletedatass():
    filldata()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from stockin where stockid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatass()
        ae.delete(0,100)
        db.close()
        
    def close():
        t.destroy()
    a=Label(t,text='stock id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=si
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()
def findss():
    filldatass()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catid,productid,pname,datein,qty from stockin where stockid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,str(data[0]))
        ce.insert(0,str(data[1]))
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedatass()
        t.destroy()
    a=Label(t,text=' stock id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=si
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='category id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='product id')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='product name ')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='datein')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def updatedatass():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select catid,productid,pname,datein,qty from stockin where stockid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,data[0])
        ce.insert(0,data[1])
        de.insert(0,data[2])
        ee.insert(0,data[3])
        fe.insert(0,str(data[4]))
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=int(be.get())
        xc=int(ce.get())
        xd=de.get()
        xe=ee.get()
        xf=int(fe.get())
        sql="update stockin set catid=%d,productid=%d,pname='%s',datein='%s',qty=%d where stockid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        t.destroy()
    a=Label(t,text='stock id')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    ab=Button(t,text='showdata',command=find)
    ab.place(x=260,y=50)
    b=Label(t,text='category id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='product id')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='product name')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='datein')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def showss():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select stockid,catid,productid,pname,datein,qty from stockin"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])

    a=Label(t,text='stockid')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='catid')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='productid')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='pname')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='datein')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='qty')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
def inserto():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('orders')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=int(be.get())
        xc=ce.get()
        xe=int(ee.get())
        xd=int(de.get())
        xg=int(ge.get())
        sql="insert into orders values('%d','%d','%s','%d','%d','%d')"%(xa,xb,xc,xd,xe,xg)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        oc.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        ge.delete(0,100)
    a=Label(t,text='orderid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='custid')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='date of order')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='catid')
    d.place(x=50,y=170)
    de=Entry(t,width=10)
    de.place(x=150,y=170)
    e=Label(t,text='productid')
    e.place(x=50,y=210)
    ee=Entry(t,width=20)
    ee.place(x=150,y=210)
    g=Label(t,text='qty')
    g.place(x=50,y=250)
    ge=Entry(t,width=20)
    ge.place(x=150,y=250)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=370)
    t.mainloop()
def removedatao():
    oc.clear()
def filldatao():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select orderid from orders"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        oc.append(i)
def deletedatao():
    filldatao()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from orders where orderid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatao()
        ae.delete(0,100)
        db.close()
        
    def close():
        removedatao()
        t.destroy()
    a=Label(t,text='orderid')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=oc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def findo():
    filldatao()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select custid,dateoforder,catid,productid,qty from orders where orderid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,str(data[0]))
        ce.insert(0,data[1])
        de.insert(0,str(data[2]))
        ee.insert(0,str(data[3]))
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedata()
        t.destroy()
    a=Label(t,text=' order id')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=oc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='customer id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='date of order')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='category id')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='productid')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def updatedatao():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select custid,dateoforder,catid,productid,qty from orders where orderid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,str(data[0]))
        ce.insert(0,data[1])
        de.insert(0,str(data[2]))
        ee.insert(0,str(data[3]))
        fe.insert(0,str(data[4]))
        db.close()
    def update():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        xb=int(be.get())
        xc=ce.get()
        xd=int(de.get())
        xe=int(ee.get())
        xf=int(fe.get())
        sql="update orders set custid=%d,dateoforder='%s',catid=%d,productid=%d,qty=%d where orderid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','updated')
        ae.delete(0,100)
        be.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
        ce.delete(0,100)
        
                    
    def close():
        t.destroy()
    a=Label(t,text='order id')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    ab=Button(t,text='showdata',command=find)
    ab.place(x=260,y=50)
    b=Label(t,text='cust id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='date of order')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='catid')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='productid')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='quantity')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='update',command=update)
    btn3.place(x=200,y=320)
    t.mainloop()
def showo():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select orderid,custid,dateoforder,catid,productid,qty from orders"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])

    a=Label(t,text='orderid')
    a.place(x=20,y=50)
    b=Label(t,width=30)
    b.place(x=500,y=50)
    c=Label(t,text='custid')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='dateoforder')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='catid')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='product')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='qty')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
def insertdi():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('billing')
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        if len(ae.get())==0 or len(be.get())==0 or len(ce.get())==0 or len(de.get())==0 or len(ee.get())==0 or len(fe.get())==0:
            messagebox.showerror("ERROR","PLS FILL THE DATA PROPERLY")
        xa=int(ae.get())
        xb=int(be.get())
        xc=int(ce.get())
        xf=int(fe.get())
        xe=int(ee.get())
        xd=int(de.get())
        sql="insert into dispatch values('%d','%d','%d','%d','%d','%d')"%(xa,xb,xc,xf,xd,xe)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','data saved')
        db.close
        dc.append(xa)
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        fe.delete(0,100)
        ee.delete(0,100)
    a=Label(t,text='dispatchid')
    a.place(x=50,y=50)
    ae=Entry(t,width=10)
    ae.place(x=150,y=50)
    b=Label(t,text='orderid')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='custid')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    f=Label(t,text='productid')
    f.place(x=50,y=180)
    fe=Entry(t,width=5)
    fe.place(x=150,y=180)
    d=Label(t,text='qty')
    d.place(x=50,y=220)
    de=Entry(t,width=10)
    de.place(x=150,y=220)
    e=Label(t,text='billamount')
    e.place(x=50,y=270)
    ee=Entry(t,width=20)
    ee.place(x=150,y=270)
    btn=Button(t,text='save',command=savedata)
    btn.place(x=50,y=320)
    t.mainloop()
def removedatadi():
    dc.clear()
def filldatadi():
    db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
    cur=db.cursor()
    sql="select dispatchno from dispatch"
    cur.execute(sql)
    data=cur.fetchall()
    for i in data:
        dc.append(i)
def deletedatadi():
    filldatadi()
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def deletedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="delete from dispatch where dispatchno=%d"%(xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('i','data deleted')
        removedatadi()
        ae.delete(0,100)
        
    def close():
        removedatadi()
        t.destroy()
    a=Label(t,text='dispatchno')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=dc
    ae.place(x=150,y=50)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn3=Button(t,text='delete',command=deletedata)
    btn3.place(x=200,y=320)
    t.mainloop()

def finddi():
    filldatadi()
    global sc
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('p1')
    def find():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        xa=int(ae.get())
        sql="select ordereid,cust,productid,qty,billamount from dispatch where dispatchno=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        be.insert(0,str(data[0]))
        ce.insert(0,str(data[1]))
        de.insert(0,str(data[2]))
        ee.insert(0,str(data[3]))
        fe.insert(0,str(data[4]))
        db.close()
    def newdata():
        ae.delete(0,100)
        be.delete(0,100)
        ce.delete(0,100)
        de.delete(0,100)
        ee.delete(0,100)
        fe.delete(0,100)
    def close():
        removedata()
        t.destroy()
    t.config(bg='red')
    a=Label(t,text='dispatch no.')
    a.place(x=50,y=50)
    ae=ttk.Combobox(t)
    ae['values']=dc
    ae.place(x=150,y=50)
    ab=Button(t,text='find',command=find)
    ab.place(x=300,y=50)
    b=Label(t,text='order id')
    b.place(x=50,y=90)
    be=Entry(t,width=10)
    be.place(x=150,y=90)
    c=Label(t,text='customer id')
    c.place(x=50,y=130)
    ce=Entry(t,width=10)
    ce.place(x=150,y=130)
    d=Label(t,text='product id')
    d.place(x=50,y=180)
    de=Entry(t,width=10)
    de.place(x=150,y=180)
    e=Label(t,text='quantity')
    e.place(x=50,y=220)
    ee=Entry(t,width=20)
    ee.place(x=150,y=220)
    f=Label(t,text='billamount')
    f.place(x=50,y=270)
    fe=Entry(t,width=10)
    fe.place(x=150,y=270)
    btn=Button(t,text='close',command=close)
    btn.place(x=50,y=320)
    btn2=Button(t,text='new',command=newdata)
    btn2.place(x=150,y=320)
    t.mainloop()
def showdi():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('Data Show')
    aa=[]
    ab=[]
    ac=[]
    ad=[]
    ae=[]
    af=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
        cur=db.cursor()
        sql="select dispatchno,ordereid,cust,productid,qty,billamount from dispatch"
        cur.execute(sql)
        data=cur.fetchall()
        global i
        for res in data:
            aa.append(res[0])
            ab.append(res[1])
            ac.append(res[2])
            ad.append(res[3])
            ae.append(res[4])
            af.append(res[5])
        db.close()
    def firstrecord():
        global i
        i=0
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
        
    def nextrecord():
        global i
        i=i+1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def prevrecord():
        global i
        i=i-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])
    def lastrecord():
        global i
        i=len(aa)-1
        b.config(text='')
        d.config(text='')
        f.config(text='')
        h.config(text='')
        beie.config(text='')
        xee.config(text='')
        
        b.config(text=aa[i])
        d.config(text=ab[i])
        f.config(text=ac[i])
        h.config(text=ad[i])
        beie.config(text=ae[i])
        xee.config(text=af[i])

    a=Label(t,text='dispatchno')
    a.place(x=20,y=50)
    b=Label(t,width=30,fg='blue')
    b.place(x=500,y=50)
    c=Label(t,text='ordereid')
    c.place(x=20,y=150)
    d=Label(t,width=30)
    d.place(x=500,y=150)
    e=Label(t,text='cust')
    e.place(x=20,y=200)
    f=Label(t,width=30)
    f.place(x=500,y=200)
    g=Label(t,text='productid')
    g.place(x=20,y=250)
    h=Label(t,width=30)
    h.place(x=500,y=250)
    bei=Label(t,text='qty')
    bei.place(x=20,y=290)
    beie=Label(t,width=20)
    beie.place(x=500,y=290)
    x=Label(t,text='billamount')
    x.place(x=20,y=340)
    xee=Label(t,width=10)
    xee.place(x=500,y=340)
    k=Button(t,text='First',command=firstrecord)
    k.place(x=100,y=400)
    n=Button(t,text='Next',command=nextrecord)
    n.place(x=200,y=400)
    p=Button(t,text='Previous',command=prevrecord)
    p.place(x=300,y=400)
    r=Button(t,text='Last',command=lastrecord)
    r.place(x=400,y=400)
    filldata()
    t.mainloop()
    
    

    
a=Label(t,text='storeinfo')
a.place(x=50,y=100)
ab=Button(t,text='insert',command=insert)
ab.place(x=120,y=100)
ab2=Button(t,text='delete',command=delete)
ab2.place(x=180,y=100)
ab3=Button(t,text='find',command=find)
ab3.place(x=240,y=100)
ab4=Button(t,text='update',command=updatedata)
ab4.place(x=300,y=100)
ab5=Button(t,text='show',command=show)
ab5.place(x=360,y=100)
b=Label(t,text='product cat')
b.place(x=50,y=170)
bb=Button(t,text='insert',command=insertcat)
bb.place(x=120,y=170)
bb2=Button(t,text='delete',command=deletecat)
bb2.place(x=180,y=170)
bb3=Button(t,text='find',command=findcat)
bb3.place(x=240,y=170)
bb4=Button(t,text='update',command=updatedatacat)
bb4.place(x=300,y=170)
bb5=Button(t,text='show',command=showcat)
bb5.place(x=360,y=170)
c=Label(t,text='products')
c.place(x=50,y=240)
cb=Button(t,text='insert',command=insertpr)
cb.place(x=120,y=240)
cb2=Button(t,text='delete',command=deletepr)
cb2.place(x=180,y=240)
cb3=Button(t,text='find',command=findpr)
cb3.place(x=240,y=240)
cb4=Button(t,text='update',command=updatedatapr)
cb4.place(x=300,y=240)
cb5=Button(t,text='show',command=showpr)
cb5.place(x=360,y=240)
d=Label(t,text='supplier')
d.place(x=50,y=310)
db=Button(t,text='insert',command=insertsp)
db.place(x=120,y=310)
db2=Button(t,text='delete',command=deletesp)
db2.place(x=180,y=310)
db3=Button(t,text='find',command=findsp)
db3.place(x=240,y=310)
db4=Button(t,text='update',command=updatedatasp)
db4.place(x=300,y=310)
db5=Button(t,text='show',command=showsp)
db5.place(x=360,y=310)
e=Label(t,text='customer')
e.place(x=50,y=380)
eb=Button(t,text='insert',command=insertcc)
eb.place(x=120,y=380)
eb2=Button(t,text='delete',command=deletedatacc)
eb2.place(x=180,y=380)
eb3=Button(t,text='find',command=findcc)
eb3.place(x=240,y=380)
eb4=Button(t,text='update')
eb4.place(x=300,y=380)
eb5=Button(t,text='show',command=showcc)
eb5.place(x=360,y=380)
f=Label(t,text='stockin',)
f.place(x=50,y=450)
fb=Button(t,text='insert',command=insertss)
fb.place(x=120,y=450)
fb2=Button(t,text='delete',command=deletedatass)
fb2.place(x=180,y=450)
fb3=Button(t,text='find',command=findss)
fb3.place(x=240,y=450)
fb4=Button(t,text='update',command=updatedatass)
fb4.place(x=300,y=450)
fb5=Button(t,text='show',command=showss)
fb5.place(x=360,y=450)
g=Label(t,text='orders')
g.place(x=50,y=520)
gb=Button(t,text='insert',command=inserto)
gb.place(x=120,y=520)
gb2=Button(t,text='delete',command=deletedatao)
gb2.place(x=180,y=520)
gb3=Button(t,text='find',command=findo)
gb3.place(x=240,y=520)
gb4=Button(t,text='update',command=updatedatao)
gb4.place(x=300,y=520)
gb5=Button(t,text='show',command=showo)
gb5.place(x=360,y=520)
h=Label(t,text='dispatch')
h.place(x=50,y=590)
hb=Button(t,text='insert',command=insertdi)
hb.place(x=120,y=590)
hb2=Button(t,text='delete',command=deletedatadi)
hb2.place(x=180,y=590)
hb3=Button(t,text='find',command=finddi)
hb3.place(x=240,y=590)
hb4=Button(t,text='update')
hb4.place(x=300,y=590)
hb5=Button(t,text='show',command=showdi)
hb5.place(x=360,y=590)
t.mainloop()
[]