import tkinter
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
import pymysql
t=tkinter.Tk()
t.geometry('500x300')
t.title('insert')
def trydash():
    x=b.get()
    if x=='storeinfo':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                xf=int(fe.get())
                xe=int(ee.get())
                xd=de.get()
                sql="insert into storeinfo values('%d','%s','%s','%d','%s','%d')"%(xa,xb,xc,xf,xd,xe)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
            a=Label(t,text='storeid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='name')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='address')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            f=Label(t,text='phone no')
            f.place(x=50,y=180)
            fe=Entry(t,width=5)
            fe.place(x=150,y=180)
            d=Label(t,text='email')
            d.place(x=50,y=220)
            de=Entry(t,width=10)
            de.place(x=150,y=220)
            e=Label(t,text='regno')
            e.place(x=50,y=270)
            ee=Entry(t,width=20)
            ee.place(x=150,y=270)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=320)
            t.mainloop()
                        
        t.config(bg='silver')
        d=Label(t,text='storeinfo',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='grey')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='productcategory':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        def insert():
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('billing')
            def savedata():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=be.get()
                xc=ce.get()
                sql="insert into productcategory values('%d','%s','%s')"%(xa,xb,xc)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('hi','data saved')
                db.close
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
            a=Label(t,text='catid')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            b=Label(t,text='categoryname')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='Discription')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            btn=Button(t,text='save',command=savedata)
            btn.place(x=50,y=180)
            t.mainloop()
        t.config(bg='gold')
        d=Label(t,text='productcategory',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue',command=insert)
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='products':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='red')
        d=Label(t,text='products',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='supplier':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='blue')
        d=Label(t,text='supplier',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='customer':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='darkgreen')
        d=Label(t,text='productcategory',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='stockin':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='aqua')
        d=Label(t,text='stockin',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='orders':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='purple')
        d=Label(t,text='orders',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
    elif x=='dispatch':
        t=tkinter.Tk()
        t.geometry('400x500')
        t.title('inventory')
        t.config(bg='orange')
        d=Label(t,text='dispatch',font=15,)
        d.place(x=50,y=110)
        a=Label(t,text='dashboard',font=60,bg='gold')
        a.place(x=50,y=50)
        c=Button(t,text='insert',width=10,bg='lightblue')
        c.place(x=250,y=150)
        b2=Button(t,text='delete',width=10,bg='lightblue')
        b2.place(x=250,y=200)
        b3=Button(t,text='find',width=10,bg='lightblue')
        b3.place(x=250,y=250)
        b4=Button(t,text='update',width=10,bg='lightblue')
        b4.place(x=250,y=300)
        b5=Button(t,text='show',width=10,bg='lightblue')
        b5.place(x=250,y=350)
        t.mainloop()
        
t.config(bg='pink')
a=Label(t,text='select table',font=30)
a.place(x=50,y=50)
b=ttk.Combobox(t)
b['values']=['storeinfo','productcategory','products','supplier','customer','stockin','orders','dispatch']
b.place(x=300,y=50)
btn=Button(t,text='enter',bg='lightblue',command=trydash)
btn.place(x=250,y=150)


t.mainloop()