
            global sc
            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select orderid,cust,productid,qty,billamount from dispatch where dispatchno=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,str(data[0]))
                ce.insert(0,str(data[1]))
                de.insert(0,str(data[2]))
                ee.insert(0,str(data[3]))
                fe.insert(0,str(data[4]))
                db.close()
            def newdata():
                ae.delete(0,100)
                be.delete(0,100)
                ce.delete(0,100)
                de.delete(0,100)
                ee.delete(0,100)
                fe.delete(0,100)
            def close():
                t.destroy()
            a=Label(t,text='dispatch no.')
            a.place(x=50,y=50)
            ae=ttk.Combobox(t)
            ae['values']=oc
            ae.place(x=150,y=50)
            ab=Button(t,text='find',command=find)
            ab.place(x=300,y=50)
            b=Label(t,text='order id')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='customer id')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='product id')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='quantity')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='billamount')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            fe.place(x=150,y=270)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn2=Button(t,text='new',command=newdata)
            btn2.place(x=150,y=320)
            t.mainloop()