            t=tkinter.Tk()
            t.geometry('800x800')
            t.title('p1')
            def find():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                sql="select custid,dateoforder,catid,productid,qty from orders where orderid=%d"%(xa)
                cur.execute(sql)
                data=cur.fetchone()
                be.insert(0,str(data[0]))
                ce.insert(0,data[1])
                de.insert(0,str(data[2]))
                ee.insert(0,str(data[3]))
                fe.insert(0,str(data[4]))
                db.close()
            def update():
                db=pymysql.connect(host='localhost',user='root',password='root',database='testdb')
                cur=db.cursor()
                xa=int(ae.get())
                xb=int(be.get())
                xc=ce.get()
                xd=int(de.get())
                xe=int(ee.get())
                xf=int(fe.get())
                sql="update orders set caustid=%d,dateoforder='%s',catid=%d,productid=%d,qty=%d where stockid=%d"%(xb,xc,xd,xe,xf,xa)
                cur.execute(sql)
                db.commit()
                messagebox.showinfo('Hi','updated')
                ae.delete(0,100)
                be.delete(0,100)
                de.delete(0,100)
                fe.delete(0,100)
                ee.delete(0,100)
                ce.delete(0,100)
                
                            
            def close():
                t.destroy()
            a=Label(t,text='order id')
            a.place(x=50,y=50)
            ae=Entry(t,width=10)
            ae.place(x=150,y=50)
            ab=Button(t,text='showdata',command=find)
            ab.place(x=260,y=50)
            b=Label(t,text='cust id')
            b.place(x=50,y=90)
            be=Entry(t,width=10)
            be.place(x=150,y=90)
            c=Label(t,text='date of order')
            c.place(x=50,y=130)
            ce=Entry(t,width=10)
            ce.place(x=150,y=130)
            d=Label(t,text='catid')
            d.place(x=50,y=180)
            de=Entry(t,width=10)
            de.place(x=150,y=180)
            e=Label(t,text='productid')
            e.place(x=50,y=220)
            ee=Entry(t,width=20)
            ee.place(x=150,y=220)
            f=Label(t,text='quantity')
            f.place(x=50,y=270)
            fe=Entry(t,width=10)
            fe.place(x=150,y=270)
            btn=Button(t,text='close',command=close)
            btn.place(x=50,y=320)
            btn3=Button(t,text='update',command=update)
            btn3.place(x=200,y=320)
            t.mainloop()